-- Ejercicio 1
CREATE TABLE TB_OBJETOS (NOMBRE VARCHAR(128), CODIGO NUMBER, FECHA_CREACION DATE, FECHA_MODIFICACION DATE, TIPO VARCHAR(23), ESQUEMA_ORIGINAL VARCHAR(128));

DECLARE
    CURSOR cur_objects IS SELECT * FROM ALL_OBJECTS;
BEGIN
    FOR v_object IN cur_objects LOOP
        INSERT INTO TB_OBJETOS VALUES (v_object.object_name, v_object.object_id, v_object.created, v_object.last_ddl_time, v_object.object_type, v_object.owner);
    END LOOP;
END;
/

-- Ejercicio 2
CREATE TABLE TB_ESTILO (TIPO_OBJETO VARCHAR(23), PREFIJO VARCHAR(20));
INSERT INTO tb_estilo VALUES ('PROCEDURE', 'PR_');

-- Ejercicio 3
ALTER TABLE TB_OBJETOS ADD ESTADO VARCHAR(10) ADD NOMBRE_CORRECTO VARCHAR(128);

/*
CREATE OR REPLACE PROCEDURE PR_COMPROBAR(ESQUEMA IN VARCHAR2) IS
    CURSOR cur_objects IS SELECT * FROM TB_OBJETOS WHERE ESQUEMA_ORIGINAL = NVL(ESQUEMA, ESQUEMA_ORIGINAL);
BEGIN
    FOR v_obj IN cur_objects LOOP
        
    END LOOP;
END;
*/
