-- Ejercicio 1
CREATE TABLE MENSAJES (
    Codigo NUMBER(20) CONSTRAINT MENSAJES_PK PRIMARY KEY,
    Texto VARCHAR(200)
);

CREATE TABLE AUDITA_MENSAJES(
    Quien VARCHAR(20),
    Como VARCHAR(20),
    Cuando DATE
);

CREATE OR REPLACE TRIGGER tr_control_mensajes 
AFTER INSERT OR DELETE OR UPDATE ON MENSAJES
BEGIN
    IF INSERTING THEN
        INSERT INTO AUDITA_MENSAJES VALUES (USER, 'INSERT', SYSDATE);
    ELSIF DELETING THEN
        INSERT INTO AUDITA_MENSAJES VALUES (USER, 'DELETE', SYSDATE);
    ELSE
        INSERT INTO AUDITA_MENSAJES VALUES (USER, 'UPDATE', SYSDATE);
    END IF;
END;
/

INSERT INTO MENSAJES VALUES (12345, 'No tiene permiso para operar en este formulario');

-- Ejercicio 2
ALTER TABLE MENSAJES ADD (TIPO VARCHAR2(20));
ALTER TABLE MENSAJES ADD CONSTRAINT TIPO_CHK CHECK(TIPO IN ('INFORMACION', 'RESTRICCION', 'ERROR', 'AVISO', 'AYUDA'));
INSERT INTO MENSAJES VALUES(1, 'Test', 'TIPO_INCORRECTO');

INSERT INTO MENSAJES VALUES (1, 'Informacion1', 'INFORMACION');
INSERT INTO MENSAJES VALUES (2, 'Informacion2', 'INFORMACION');
INSERT INTO MENSAJES VALUES (3, 'Restriccion1', 'RESTRICCION');
INSERT INTO MENSAJES VALUES (4, 'Restriccion2', 'RESTRICCION');
INSERT INTO MENSAJES VALUES (5, 'Error1', 'ERROR');
INSERT INTO MENSAJES VALUES (6, 'Error2', 'ERROR');
INSERT INTO MENSAJES VALUES (7, 'Aviso1', 'AVISO');
INSERT INTO MENSAJES VALUES (8, 'Aviso2', 'AVISO');
INSERT INTO MENSAJES VALUES(9, 'Ayuda1', 'AYUDA');
INSERT INTO MENSAJES VALUES (10, 'Ayuda2', 'AYUDA');

CREATE TABLE MENSAJES_Info (
    Tipo VARCHAR(30) CONSTRAINT MENSAJES_INFO_PK PRIMARY KEY,
    Cuantos_Mensajes NUMBER(2),
    Ultimo VARCHAR(200)
);
INSERT INTO MENSAJES_Info(Tipo, Cuantos_Mensajes) SELECT TIPO, COUNT(*) FROM MENSAJES GROUP BY TIPO;

CREATE OR REPLACE TRIGGER tr_count_mensajes
AFTER INSERT OR DELETE OR UPDATE ON MENSAJES FOR EACH ROW
BEGIN
    IF INSERTING THEN
        UPDATE MENSAJES_Info SET Cuantos_Mensajes = Cuantos_Mensajes + 1, Ultimo = :new.texto WHERE :new.tipo = TIPO;
    ELSIF DELETING THEN
        UPDATE MENSAJES_Info SET Cuantos_Mensajes = Cuantos_Mensajes - 1, Ultimo = NULL WHERE :old.tipo = TIPO;
    ELSE
        UPDATE MENSAJES_Info SET Cuantos_Mensajes = Cuantos_Mensajes + 1, Ultimo = :new.texto WHERE :new.tipo = TIPO;
        UPDATE MENSAJES_Info SET Cuantos_Mensajes = Cuantos_Mensajes - 1, Ultimo = NULL WHERE :old.tipo = TIPO;
    END IF;
END;
/

INSERT INTO MENSAJES VALUES (11, 'Informacion3', 'INFORMACION');
UPDATE MENSAJES SET TIPO='AVISO' where Codigo=11;
DELETE FROM MENSAJES WHERE Codigo=11;

-- Ejercicio 3
CREATE TABLE MENSAJES_TEXTO(
    codigo NUMBER(20),
    texto VARCHAR2(200)
);
INSERT INTO MENSAJES_TEXTO SELECT Codigo, Texto FROM MENSAJES;

CREATE TABLE MENSAJES_TIPO(
    codigo NUMBER(20),
    tipo VARCHAR2(30)
);
INSERT INTO MENSAJES_TIPO SELECT Codigo, Tipo FROM MENSAJES;

DROP TABLE MENSAJES;

CREATE VIEW MENSAJES AS SELECT m1.CODIGO, m1.TEXTO, m2.TIPO FROM MENSAJES_TEXTO m1, MENSAJES_TIPO m2 WHERE m1.codigo=m2.codigo;

CREATE OR REPLACE TRIGGER tr_insert_mensajes_view
INSTEAD OF INSERT ON MENSAJES
FOR EACH ROW
BEGIN
    INSERT INTO MENSAJES_TEXTO VALUES (:new.codigo, :new.texto);
    INSERT INTO MENSAJES_TIPO VALUES (:new.codigo, :new.tipo);
END;
/

SELECT * FROM MENSAJES;
INSERT INTO MENSAJES VALUES (12, 'Informacion4', 'INFORMACION');

-- Ejercicio 4
CREATE TABLE MENSAJES_BORRADOS(
    codigo NUMBER(20),
    texto VARCHAR2(200)
);

CREATE OR REPLACE TRIGGER tr_mensajes_borrados
AFTER DELETE ON MENSAJES_TEXTO FOR EACH ROW
BEGIN
    INSERT INTO MENSAJES_BORRADOS VALUES (:old.codigo, :old.texto);
END;
/

DELETE FROM MENSAJES_TEXTO WHERE CODIGO=10;

-- Ejercicio 5
BEGIN
    DBMS_SCHEDULER.CREATE_JOB (
        job_name => 'limpieza',
        job_type => 'PLSQL_BLOCK',
        job_action => 'BEGIN DELETE FROM MENSAJES_BORRADOS; END;',
        start_date => SYSDATE,
        repeat_interval => 'FREQ=SECONDLY;INTERVAL=120',
        enabled => TRUE
    );
END;
/


