-- Ejercicio 1
CREATE TABLE TABLAS (
    propietario VARCHAR2(128) NOT NULL,
    nombre VARCHAR2(128) NOT NULL
);

-- Ejercicio 2
DESCRIBE USER_TABLES;

CREATE OR REPLACE PROCEDURE PR_RECORRE_1 IS
CURSOR c_tablas IS SELECT TABLE_NAME FROM USER_TABLES;
BEGIN
    FOR v_tabla in c_tablas LOOP
        INSERT INTO TABLAS VALUES (USER, v_tabla.table_name);
    END LOOP;
END;
/

EXEC PR_RECORRE_1();
SELECT * FROM TABLAS;
DELETE FROM TABLAS;

-- Ejercicio 3
DESCRIBE ALL_TABLES;

CREATE OR REPLACE PROCEDURE PR_RECORRE_2 IS
CURSOR c_tablas IS SELECT OWNER, TABLE_NAME FROM ALL_TABLES;
BEGIN
    FOR v_tabla in c_tablas LOOP
        INSERT INTO TABLAS VALUES (v_tabla.owner, v_tabla.table_name);
    END LOOP;
END;
/

EXEC PR_RECORRE_2();
SELECT * FROM TABLAS;
DELETE FROM TABLAS;

-- Ejercicio 4
CREATE OR REPLACE PROCEDURE PR_RECORRE_3 (P_MODE IN NUMBER) IS
CURSOR c_tablas IS SELECT OWNER, TABLE_NAME FROM ALL_TABLES WHERE OWNER = DECODE(P_MODE, 0, OWNER, USER);
BEGIN
    IF P_MODE IS NULL THEN 
        INSERT INTO TABLAS VALUES ('ERROR', 'SE DEBE PROPORCIONAR UN VALOR EN P_MODE');
    ELSE
        FOR v_tabla in c_tablas LOOP
            INSERT INTO TABLAS VALUES (v_tabla.owner, v_tabla.table_name);
        END LOOP;
    END IF;
END;
/

EXEC PR_RECORRE_3(0);
SELECT * FROM TABLAS;
DELETE FROM TABLAS;

EXEC PR_RECORRE_3(2);
SELECT * FROM TABLAS;
DELETE FROM TABLAS;

EXEC PR_RECORRE_3(null);
SELECT * FROM TABLAS;
DELETE FROM TABLAS;

-- Ejercicio 5
SET SERVEROUTPUT ON;
BEGIN
    evaluar_procedimiento('PR_RECORRE_1');
END;
/
BEGIN
    evaluar_procedimiento('PR_RECORRE_2');
END;
/
BEGIN
    evaluar_procedimiento('PR_RECORRE_3');
END;
/
