CREATE TABLE USUARIO (
    NOMBRE VARCHAR2(16) PRIMARY KEY,
    CLAVE VARCHAR2(16)
);

CREATE TABLE HISTORIAL (
    NOMBRE VARCHAR2(16),
    CLAVE VARCHAR2(16),
    BAJA DATE
);

CREATE TABLE VULNERABLE (
    NOMBRE VARCHAR2(16),
    FOREIGN KEY (NOMBRE) REFERENCES USUARIO(NOMBRE)
);

SET SERVEROUTPUT ON;

-- Ejercicio 1
CREATE OR REPLACE TRIGGER tr_baja
AFTER DELETE OR UPDATE ON USUARIO FOR EACH ROW
BEGIN
    INSERT INTO HISTORIAL VALUES (:old.nombre, :old.clave, SYSDATE);
END;
/

INSERT INTO USUARIO VALUES ('Juan', '1234');
DELETE FROM USUARIO WHERE NOMBRE = 'Juan';
SELECT * FROM HISTORIAL;

INSERT INTO USUARIO VALUES ('Antonio', '1234');
UPDATE USUARIO SET NOMBRE = 'MANUEL' WHERE NOMBRE = 'Antonio';
SELECT * FROM HISTORIAL;

-- Ejercicio 2
CREATE OR REPLACE FUNCTION CLAVE_VULNERABLE (p_nombre IN VARCHAR2)
RETURN BOOLEAN IS
v_count INTEGER;
CURSOR c_claves IS SELECT u.clave og, h.clave ant FROM USUARIO u, HISTORIAL h WHERE u.nombre = h.nombre AND u.nombre = p_nombre;
BEGIN
    SELECT COUNT(*) INTO v_count FROM HISTORIAL WHERE nombre = p_nombre;
    IF v_count = 0 THEN 
        RAISE_APPLICATION_ERROR(-20001, 'USUARIO_INICIAL');
    END IF;
    
    FOR v_clave IN c_claves LOOP 
        IF v_clave.og = v_clave.ant THEN
            RETURN TRUE;
        END IF;
    END LOOP;
    RETURN FALSE;
END;
/

BEGIN
    IF CLAVE_VULNERABLE('MANUEL') THEN
        DBMS_OUTPUT.PUT_LINE('TRUE');
    ELSE
        DBMS_OUTPUT.PUT_LINE('FALSE');
    END IF;
END;
/

-- Ejercicio 3
CREATE OR REPLACE PROCEDURE DETECTA_VULNERABLE IS
no_user EXCEPTION;
PRAGMA EXCEPTION_INIT(no_user, -20001);
CURSOR c_usuarios IS SELECT nombre FROM USUARIO;
BEGIN
    DELETE FROM VULNERABLE;
    FOR v_usuario IN c_usuarios LOOP
        BEGIN 
            IF CLAVE_VULNERABLE(v_usuario.nombre) THEN
                INSERT INTO VULNERABLE VALUES (v_usuario.nombre);
            END IF;
        EXCEPTION
            WHEN no_user THEN
                NULL;
        END;
    END LOOP;
END;
/

EXEC DETECTA_VULNERABLE();

-- Ejercicio 4
CREATE OR REPLACE PACKAGE EXAMEN AS

    PROCEDURE ELIMINA_USUARIO(p_nombre VARCHAR2);

END EXAMEN;
/

-- Ejercicio 5

CREATE OR REPLACE PACKAGE BODY EXAMEN AS
    
    PROCEDURE ELIMINA_USUARIO(p_nombre VARCHAR2) IS
    v_count INTEGER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM USUARIO WHERE nombre = p_nombre;
        IF v_count = 0 THEN
            RAISE_APPLICATION_ERROR(-20002, 'USUARIO_DESCONOCIDO');
        END IF;
        
        EXECUTE IMMEDIATE 'ALTER TRIGGER tr_baja DISABLE';
        DELETE FROM VULNERABLE WHERE nombre = p_nombre;
        DELETE FROM HISTORIAL WHERE nombre = p_nombre;
        DELETE FROM USUARIO WHERE nombre = p_nombre;
        EXECUTE IMMEDIATE 'ALTER TRIGGER tr_baja ENABLE';
    END;

END EXAMEN;
/

EXEC EXAMEN.elimina_usuario('Pepe');