-- Prueba Triggers
CREATE TABLE MOVIMIENTOS (
    pieza NUMBER,
    fecha DATE,
    almacen VARCHAR2(15),
    constraint movimientos_pk PRIMARY KEY (pieza, fecha)
);

CREATE TABLE COPIA_MOVIMIENTOS (
    pieza NUMBER,
    fecha DATE,
    almacen VARCHAR2(15)
);

CREATE VIEW MOVIMIENTOS_HOY AS SELECT * FROM MOVIMIENTOS WHERE fecha = SYSDATE;

-- Ejercicio 1
CREATE OR REPLACE TRIGGER TR_COPIA_MOV
AFTER INSERT OR DELETE OR UPDATE ON MOVIMIENTOS FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO COPIA_MOVIMIENTOS VALUES(:new.pieza, :new.fecha, :new.almacen);
    ELSIF DELETING THEN
        DELETE FROM COPIA_MOVIMIENTOS WHERE pieza = :old.pieza AND fecha = :old.fecha AND almacen = :old.almacen;
    ELSIF UPDATING THEN
        UPDATE COPIA_MOVIMIENTOS SET pieza = :new.pieza, fecha = :new.fecha, almacen = :new.almacen
            WHERE pieza = :old.pieza AND fecha = :old.fecha AND almacen = :old.almacen;
    END IF;
END;
/

-- Ejercicio 2
CREATE OR REPLACE TRIGGER TR_VISTA
INSTEAD OF INSERT OR DELETE OR UPDATE ON MOVIMIENTOS_HOY FOR EACH ROW
BEGIN
    IF INSERTING THEN
        INSERT INTO COPIA_MOVIMIENTOS VALUES(:new.pieza, :new.fecha, :new.almacen);
    ELSIF DELETING THEN
        DELETE FROM COPIA_MOVIMIENTOS WHERE pieza = :old.pieza AND fecha = :old.fecha AND almacen = :old.almacen;
    ELSIF UPDATING THEN
        UPDATE COPIA_MOVIMIENTOS SET pieza = :new.pieza, fecha = :new.fecha, almacen = :new.almacen
            WHERE pieza = :old.pieza AND fecha = :old.fecha AND almacen = :old.almacen;
    END IF;
END;
/

-- Prueba PL/SQL
CREATE TABLE INFO_TRIGGERS (
    NOMBRE VARCHAR2(128) PRIMARY KEY,
    TABLA VARCHAR2(128),
    VALIDO CHAR(1) CHECK(VALIDO IN ('S', 'N'))
);

CREATE TABLE INFO_TABLAS (
    NOMBRE VARCHAR2(128) PRIMARY KEY
);

CREATE OR REPLACE PACKAGE PKG_MANIPULA AS
    PROCEDURE PR_INSERTA_TRIGGER(P_NOMBRE IN VARCHAR2, P_TABLA IN VARCHAR2, P_VALIDO IN VARCHAR2);
    PROCEDURE PR_INSERTA_TRIGGER_2(P_NOMBRE IN VARCHAR2, P_TABLA IN VARCHAR2, P_VALIDO IN VARCHAR2);
END;
/

CREATE OR REPLACE PACKAGE BODY PKG_MANIPULA AS
    PROCEDURE PR_INSERTA_TRIGGER(P_NOMBRE IN VARCHAR2, P_TABLA IN VARCHAR2, P_VALIDO IN VARCHAR2) IS
    BEGIN
        INSERT INTO INFO_TRIGGERS VALUES (P_NOMBRE, P_TABLA, P_VALIDO);
        COMMIT;
    END;
    
    PROCEDURE PR_INSERTA_TRIGGER_2(P_NOMBRE IN VARCHAR2, P_TABLA IN VARCHAR2, P_VALIDO IN VARCHAR2) IS
    parent_key_not_found EXCEPTION;
    PRAGMA EXCEPTION_INIT(parent_key_not_found, -02291);
    BEGIN
        INSERT INTO INFO_TRIGGERS VALUES (P_NOMBRE, P_TABLA, P_VALIDO);
        COMMIT;
    EXCEPTION
        WHEN parent_key_not_found THEN
            INSERT INTO INFO_TABLAS VALUES (P_TABLA);
            PR_INSERTA_TRIGGER(P_NOMBRE, P_TABLA, P_VALIDO);
    END;
END;
/

ALTER TABLE INFO_TRIGGERS ADD CONSTRAINT info_tabla_fk FOREIGN KEY (TABLA) references INFO_TABLAS (NOMBRE);

EXEC PKG_MANIPULA.pr_inserta_trigger_2('TR_TEST', 'TB_TEST', 'N');