CREATE TABLE REGIONS (
    REGION_ID      NUMBER        CONSTRAINT REGIONS_PK PRIMARY KEY,
    REGION_NAME    VARCHAR2(25)
);


CREATE TABLE COUNTRIES (
    COUNTRY_ID     CHAR(2)       CONSTRAINT COUNTRIES_PK PRIMARY KEY,
    COUNTRY_NAME   VARCHAR2(40),
    REGION_ID      NUMBER,
    CONSTRAINT COUNTRIES_REGION_FK
        FOREIGN KEY (REGION_ID)
        REFERENCES REGIONS (REGION_ID)
);


CREATE TABLE LOCATIONS (
    LOCATION_ID    NUMBER(4)     CONSTRAINT LOCATIONS_PK PRIMARY KEY,
    STREET_ADDRESS VARCHAR2(40),
    POSTAL_CODE    VARCHAR2(12),
    CITY           VARCHAR2(30)  CONSTRAINT LOCATIONS_CITY_NN NOT NULL,
    STATE_PROVINCE VARCHAR2(25),
    COUNTRY_ID     CHAR(2),
    CONSTRAINT LOCATIONS_COUNTRY_FK
        FOREIGN KEY (COUNTRY_ID)
        REFERENCES COUNTRIES (COUNTRY_ID)
);

CREATE TABLE JOBS (
    JOB_ID      VARCHAR2(10)  CONSTRAINT JOBS_PK PRIMARY KEY,
    JOB_TITLE   VARCHAR2(35)  CONSTRAINT JOBS_TITLE_NN NOT NULL,
    MIN_SALARY  NUMBER(6),
    MAX_SALARY  NUMBER(6)
);


CREATE TABLE DEPARTMENTS (
    DEPARTMENT_ID   NUMBER(4)    CONSTRAINT DEPARTMENTS_PK PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR2(30) CONSTRAINT DEPT_NAME_NN NOT NULL,
    MANAGER_ID      NUMBER(6),
    LOCATION_ID     NUMBER(4),
    CONSTRAINT DEPT_LOCATION_FK
        FOREIGN KEY (LOCATION_ID)
        REFERENCES LOCATIONS (LOCATION_ID)
);



/*======================================================
  TABLA EMPLOYEES
======================================================*/

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID    NUMBER(6)     CONSTRAINT EMPLOYEES_PK PRIMARY KEY,
    FIRST_NAME     VARCHAR2(20),
    LAST_NAME      VARCHAR2(25)  CONSTRAINT EMP_LAST_NAME_NN NOT NULL,
    EMAIL          VARCHAR2(25)  CONSTRAINT EMP_EMAIL_NN NOT NULL,
    PHONE_NUMBER   VARCHAR2(20),
    HIRE_DATE      DATE          CONSTRAINT EMP_HIRE_DATE_NN NOT NULL,
    JOB_ID         VARCHAR2(10)  CONSTRAINT EMP_JOB_NN NOT NULL,
    SALARY         NUMBER(8,2),
    COMMISSION_PCT NUMBER(2,2),
    MANAGER_ID     NUMBER(6),
    DEPARTMENT_ID  NUMBER(4),

    CONSTRAINT EMP_JOB_FK
        FOREIGN KEY (JOB_ID)
        REFERENCES JOBS (JOB_ID),

    CONSTRAINT EMP_DEPT_FK
        FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENTS (DEPARTMENT_ID),

    CONSTRAINT EMP_MANAGER_FK
        FOREIGN KEY (MANAGER_ID)
        REFERENCES EMPLOYEES (EMPLOYEE_ID)
);

ALTER TABLE DEPARTMENTS
ADD CONSTRAINT DEPT_MANAGER_FK
FOREIGN KEY (MANAGER_ID)
REFERENCES EMPLOYEES (EMPLOYEE_ID);


CREATE TABLE JOB_HISTORY (
    EMPLOYEE_ID   NUMBER(6)   CONSTRAINT JH_EMP_NN NOT NULL,
    START_DATE    DATE        CONSTRAINT JH_START_NN NOT NULL,
    END_DATE      DATE        CONSTRAINT JH_END_NN NOT NULL,
    JOB_ID        VARCHAR2(10) CONSTRAINT JH_JOB_NN NOT NULL,
    DEPARTMENT_ID NUMBER(4),

    CONSTRAINT JOB_HISTORY_PK
        PRIMARY KEY (EMPLOYEE_ID, START_DATE),

    CONSTRAINT JH_EMP_FK
        FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEES (EMPLOYEE_ID),

    CONSTRAINT JH_JOB_FK
        FOREIGN KEY (JOB_ID)
        REFERENCES JOBS (JOB_ID),

    CONSTRAINT JH_DEPT_FK
        FOREIGN KEY (DEPARTMENT_ID)
        REFERENCES DEPARTMENTS (DEPARTMENT_ID)
);